133 poll in browser
privacyidea/keycloak-provider pull request #136
Opened 2023-04-06 13:25 UTC by lukasmatusiewicz

todo: fix the postMessage.
todo: worker's callbacks.

2023-05-22 12:08 UTC, nilsbehlen requested changes
Please add an optional URL config option that will be used for poll in browser is set.

2023-05-22 12:08 UTC, nilsbehlen commented on src/main/resources/theme-resources/resources/pi-pollTransaction.worker.js
> +                setInterval("pollTransactionInBrowser()", 2000);
2s intervals are too high, we could do this every 300 or 500ms

2023-05-22 12:08 UTC, nilsbehlen commented on src/main/resources/theme-resources/templates/privacyIDEA.ftl
> +                            <#if transactionID?? && !(transactionID = "") && !(piServerUrl = "") && (pollInBrowserFailed = false)>
Please add some comment describing the rationale behind the condition

2023-05-22 12:08 UTC, nilsbehlen commented on src/main/resources/theme-resources/templates/privacyIDEA.ftl
> +                            <#if transactionID?? && !(transactionID = "") && !(piServerUrl = "") && (pollInBrowserFailed = false)>
or generally how poll in browser (that section) fits in with the rest of the code

2023-05-22 12:08 UTC, nilsbehlen commented on src/main/resources/theme/privacyidea/login/theme.properties
> +scripts=js/pi-webauthn.js, js/pi-u2f.js, js/pi-pollTransaction.worker.js, js/pi-webWorkerUtils.js
js/pi-webWorkerUtils.js is not in this PR. Is the file not needed/removed?

2023-05-22 12:08 UTC, nilsbehlen commented on src/main/resources/theme-resources/templates/privacyIDEA.ftl
> +                                        console.log("Trying to to poll in the browser...");
Please remove this. Only log if an error occurs

2023-05-22 12:08 UTC, nilsbehlen commented on src/main/resources/theme-resources/templates/privacyIDEA.ftl
> +                                                            console.log(data.message);
remove pls, only log on error

2023-05-23 12:58 UTC, lukasmatusiewicz commented on src/main/resources/theme-resources/resources/pi-pollTransaction.worker.js
> +                setInterval("pollTransactionInBrowser()", 2000);
changed in [a1d037b](https://github.com/privacyidea/keycloak-provider/pull/136/commits/a1d037b7632e149529ad2480af03f01a88a1d8e5)

2023-05-23 13:04 UTC, lukasmatusiewicz commented on src/main/resources/theme/privacyidea/login/theme.properties
> +scripts=js/pi-webauthn.js, js/pi-u2f.js, js/pi-pollTransaction.worker.js, js/pi-webWorkerUtils.js
fixed in [e0018db](https://github.com/privacyidea/keycloak-provider/pull/136/commits/e0018db038754e4c330ee95d22f710397e64f239)

2023-05-23 13:04 UTC, lukasmatusiewicz commented on src/main/resources/theme-resources/templates/privacyIDEA.ftl
> +                            <#if transactionID?? && !(transactionID = "") && !(piServerUrl = "") && (pollInBrowserFailed = false)>
[597364c](https://github.com/privacyidea/keycloak-provider/pull/136/commits/597364c9dfa21e94e3b13f5ee2f7f24913408180)

2023-05-23 13:05 UTC, lukasmatusiewicz commented on src/main/resources/theme-resources/templates/privacyIDEA.ftl
> +                                        console.log("Trying to to poll in the browser...");
fixed

2023-05-23 13:07 UTC, lukasmatusiewicz commented on src/main/resources/theme-resources/templates/privacyIDEA.ftl
> +                                                            console.log(data.message);
[7cbc8a1](https://github.com/privacyidea/keycloak-provider/pull/136/commits/7cbc8a17037a70277a2ed2dfb9a4d3246b4eecbf)

2023-05-26 08:28 UTC, nilsbehlen approved these changes

2023-07-31 10:15 UTC, merged