Make sure correct Configuration and PrivacyIDEA instances are used
privacyidea/keycloak-provider pull request #140
Opened 2023-05-30 14:52 UTC by gryffus

Introduce new loadConfiguration instead of createInstance, that makes sure correct instance of PrivacyIDEA and Configuration are used.

This method is later used in both action() and authenticate().

Fixes https://github.com/privacyidea/keycloak-provider/issues/139

2023-06-02 13:43 UTC, nilsbehlen requested changes

2023-06-02 13:43 UTC, nilsbehlen commented on src/main/java/org/privacyidea/authenticator/PrivacyIDEAAuthenticator.java
> +
please remove the blank linkes here, in L109, 121, 125 (see formatting of other code)

2023-06-02 13:43 UTC, nilsbehlen commented on src/main/java/org/privacyidea/authenticator/PrivacyIDEAAuthenticator.java
> +
please remove blank line

2023-06-02 13:43 UTC, nilsbehlen commented on src/main/java/org/privacyidea/authenticator/PrivacyIDEAAuthenticator.java
> +            piInstanceMap.putIfAbsent(kcRealm, pair);
if dont think we should use `putIfAbent` here, because we want to be able to overwrite the pair if the configuration for the realm changes, see the condition in the if `incomingHash != currentPair.configuration().configHash()`.
Using `put` will achieve that.

2023-06-08 11:57 UTC, gryffus commented
I have refactored the code, removed the blank lines and used "put". Should be fine now.

2023-06-12 11:38 UTC, merged