162 feature send static pass
privacyidea/keycloak-provider pull request #164
Opened 2023-11-02 13:57 UTC by lukasmatusiewicz

closing #162

2023-11-02 14:00 UTC, lukasmatusiewicz commented
add config description

2023-11-06 10:18 UTC, nilsbehlen requested changes

2023-11-06 10:18 UTC, nilsbehlen commented on src/main/java/org/privacyidea/authenticator/PrivacyIDEAAuthenticator.java
> +            if (config.staticPass() != null)
the static pass can not be null. If the config input is empty, it should be interpreted as empty string. Therefore, `config.staticPass()` should always return a string. That makes the check unnecessary.

2023-11-06 10:39 UTC, lukasmatusiewicz commented on src/main/java/org/privacyidea/authenticator/PrivacyIDEAAuthenticator.java
> +            if (config.staticPass() != null)
[0cd5676](https://github.com/privacyidea/keycloak-provider/pull/164/commits/0cd56765465bca7abb3c02419fbbf821f20dd241)

2023-11-06 10:39 UTC, merged