Cleanup and update
privacyidea/keycloak-provider pull request #195
Opened 2024-11-04 11:54 UTC by lukasmatusiewicz

This pull request includes several updates and improvements to the privacyIDEA provider for Keycloak, focusing on upgrading dependencies, refactoring code, and enhancing the user interface. The most important changes include updating dependencies in the `pom.xml` file, refactoring constants for consistency, removing U2F support, and adding new JavaScript functionality for front-end interactions.

### Dependency Updates:
* Updated `keycloak-core` dependency version from `23.0.4` to `24.0.3` in `pom.xml`.
* Updated `okhttp` dependency version from `4.9.1` to `5.0.0-alpha.3` in `pom.xml`.

### Code Refactoring:
* Refactored constants in `Const.java` for consistent naming conventions (e.g., `push_available` to `pushAvailable`).
* Removed U2F support from `PrivacyIDEAAuthenticator.java` by deleting related constants, methods, and attributes. [[1]](diffhunk://#diff-0e8cdfe80e57354c310e68c2cc4c27f9b3caac83347d0e211e9f9aff6ca10c3aL50-L54) [[2]](diffhunk://#diff-0e8cdfe80e57354c310e68c2cc4c27f9b3caac83347d0e211e9f9aff6ca10c3aL81-L82) [[3]](diffhunk://#diff-0e8cdfe80e57354c310e68c2cc4c27f9b3caac83347d0e211e9f9aff6ca10c3aL213) [[4]](diffhunk://#diff-0e8cdfe80e57354c310e68c2cc4c27f9b3caac83347d0e211e9f9aff6ca10c3aL361-L363) [[5]](diffhunk://#diff-0e8cdfe80e57354c310e68c2cc4c27f9b3caac83347d0e211e9f9aff6ca10c3aL376) [[6]](diffhunk://#diff-0e8cdfe80e57354c310e68c2cc4c27f9b3caac83347d0e211e9f9aff6ca10c3aL416-R410) [[7]](diffhunk://#diff-0e8cdfe80e57354c310e68c2cc4c27f9b3caac83347d0e211e9f9aff6ca10c3aL488) [[8]](diffhunk://#diff-0e8cdfe80e57354c310e68c2cc4c27f9b3caac83347d0e211e9f9aff6ca10c3aL531-L545) [[9]](diffhunk://#diff-0e8cdfe80e57354c310e68c2cc4c27f9b3caac83347d0e211e9f9aff6ca10c3aL568)
* Removed U2F from the list of preferred token types in `PrivacyIDEAAuthenticatorFactory.java`.

### Front-End Enhancements:
* Added new CSS styles in `pi-form.css` for better UI presentation.
* Introduced new JavaScript functions in `pi-eventListeners.js`, `pi-form.js`, and `pi-utils.js` to handle event listeners, form submissions, and WebAuthn interactions. [[1]](diffhunk://#diff-f4ba643edb04fa6ade31f1ad8953460ca194c12bf476cf0f0e67e8e5d1b62ddfR1-R88) [[2]](diffhunk://#diff-b01a9e10ae9ec4e326f5043fde83b835c818db2b722d32d5791fa22e42fab1cdR1-R103) [[3]](diffhunk://#diff-8cdb7293422ead69b4b473c00b4ba16214c69a2b6c45bfce5858ce41801f3575R1-R64)
* Updated `privacyIDEA.ftl` template to include new CSS and JavaScript files for enhanced functionality.

### Documentation Update:
* Updated `README.md` to reflect the change from 2FA to MFA terminology.

These changes collectively improve the functionality, maintainability, and user experience of the privacyIDEA provider for Keycloak.

2024-11-04 12:16 UTC, lukasmatusiewicz commented
last tests...

2024-11-04 12:21 UTC, lukasmatusiewicz commented
closing #187

2024-11-11 09:11 UTC, nilsbehlen requested changes

2024-11-11 09:11 UTC, nilsbehlen commented on src/main/java/org/privacyidea/authenticator/PrivacyIDEAAuthenticatorFactory.java
> +                        "This setting is mutually exclusive with sending any password and will take precedence over both.");
the formatting is off here

2024-11-11 11:05 UTC, lukasmatusiewicz commented on src/main/java/org/privacyidea/authenticator/PrivacyIDEAAuthenticatorFactory.java
> +                        "This setting is mutually exclusive with sending any password and will take precedence over both.");
[974f064](https://github.com/privacyidea/keycloak-provider/pull/195/commits/974f0640ed06c6e1624fa283f8f8612d3b615fae)

2024-11-11 11:16 UTC, nilsbehlen commented on src/main/java/org/privacyidea/authenticator/PrivacyIDEAAuthenticator.java
> +    @Override public void authenticate(AuthenticationFlowContext context)
this is wrong formatting

2024-11-11 11:44 UTC, lukasmatusiewicz commented on src/main/java/org/privacyidea/authenticator/PrivacyIDEAAuthenticator.java
> +    @Override public void authenticate(AuthenticationFlowContext context)
[0bd9b91](https://github.com/privacyidea/keycloak-provider/pull/195/commits/0bd9b91d93771b6f1578322981dc4b3b60a83104)

2024-11-11 11:59 UTC, nilsbehlen approved these changes

2024-11-11 11:59 UTC, merged